spring:
  datasource:
    url: jdbc:mysql://find-own.c966a4m2k7ff.ap-northeast-2.rds.amazonaws.com/findown
    username: admin1234
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.naver.com
    port: 465
    username: jwl5015@naver.com
    password: dlawjddn1234!
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          starttls:
            enable: true
  security:
    user:
      name: dlawjddn
      password: dlawjddn
  data:
    redis:
      host: 127.0.0.1
      port: 6379


generate:
  random_string:
    length: 8
    start-bound: 33
    end-bound: 94

jwt:
  secret: 16d3ed2a16dd8c25b3b2f207c00071c8ca69a7a8bd4e9eb7d60f817147f86057ce309de62d3b9b404afc4bf7cebbfb023c80dcf1b4f3c33fc03f75768a2b6d07
  access-token:
    expiration: 86400000
  refresh-token:
    expiration: 604800000

logging:
  level:
    #org.springframework.security: DEBUG
    web: DEBUG

